### ISSUE TITLE
Attack Tarcom is set to 0 when loading a map

### ISSUE THREAD

**Issue by FlaminWrap** [Nyerguds/CnCTDRAMapEditor#3]
### How to reproduce
* Create a map and create a team with an attack Tarcom instruction
* Set the value in the attack Tarcom instruction to 16384 or something valid
* Save the map
* Close the editor
* Open the editor and open the map you have just created
* The attack Tarcom command has been set to 0

**Comment by Nyerguds** [comment]
It appears that the value does not actually get cleared; it just gets parsed incorrectly, as `byte` type. Your example just happens to end up as 0 when parsed to byte since it's exactly divisible by 256.

Seems this parsing is a leftover of the original editor code. The fix is in the pipeline for the next release.
